//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArabaBendeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestID { get; set; }
        public int PersonID { get; set; }
        public Nullable<int> DurationCheck { get; set; }
        public int VehicleID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string RequestType { get; set; }
    }
}
